INSERT INTO USER (USER_ID, USERNAME, PASSWORD, NICKNAME, ACTIVATED) VALUES (101, 'admin', '$2a$08$lDnHPz7eUkSi6ao14Twuau08mzhWrL4kyZGGU5xfiGALO/Vxd5DOi', 'admin', 1);
INSERT INTO USER (USER_ID, USERNAME, PASSWORD, NICKNAME, ACTIVATED) VALUES (102, 'user', '$2a$08$UkVvwpULis18S19S5pZFn.YHPZt3oaqHZnDwqbCW9pft6uFtkXKDC', 'user', 1);

INSERT INTO AUTHORITY (AUTHORITY_NAME) values ('ROLE_USER');
INSERT INTO AUTHORITY (AUTHORITY_NAME) values ('ROLE_ADMIN');

INSERT INTO USER_AUTHORITIES (USER_USER_ID, AUTHORITIES_AUTHORITY_NAME) values (101, 'ROLE_USER');
INSERT INTO USER_AUTHORITIES (USER_USER_ID, AUTHORITIES_AUTHORITY_NAME) values (101, 'ROLE_ADMIN');
INSERT INTO USER_AUTHORITIES (USER_USER_ID, AUTHORITIES_AUTHORITY_NAME) values (102, 'ROLE_USER');